apiVersion: 1

deleteDatasources:
  - name: Prometheus
    type: prometheus

datasources:
  - name: Prometheus
    uid: PrometheusDatasource
    type: prometheus
    access: proxy
    url: ${GF_PROMETHEUS_URL}
    basicAuth: false
    isDefault: true
    editable: false
    jsonData:
      tlsSkipVerify: true
      timeInterval: 15s
